version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
      - ollama

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  mysql_db:
    build: ./database
    ports:
      - "3306:3306"

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"

  wazuh:
    build: ./wazuh
    ports:
      - "1514:1514/udp"
      - "55000:55000"

  suricata:
    build: ./suricata
    network_mode: "host"

  zerotrust:
    build: ./zerotrust
    ports:
      - "6262:6262"
